const fs = require('fs');
const { sequelize } = require('./src/models');
(async () => {
  await sequelize.authenticate();
  const models = sequelize.models;
  const mappersDir = '../frontend/src/services/mappers';
  const mappers = fs.readdirSync(mappersDir).filter(f => f.endsWith('.js'));
  
  for (const modelName of Object.keys(models)) {
    const model = models[modelName];
    const attrs = model.rawAttributes;
    const requiredAttrs = Object.keys(attrs).filter(k => 
      attrs[k].allowNull === false && 
      !attrs[k]._autoGenerated && 
      attrs[k].defaultValue === undefined && 
      k !== 'id' && 
      k !== 'createdAt' && 
      k !== 'updatedAt' && 
      k !== 'deletedAt' && 
      k !== 'tenantId' && 
      k !== 'branchId' &&
      k !== 'userId' // usually handled by Auth token
    );
    
    // Find matching mapper
    const mapperFile = mappers.find(m => m.toLowerCase().startsWith(modelName.toLowerCase() + 'm'));
    if (!mapperFile) {
      continue;
    }
    const mapperContent = fs.readFileSync(mappersDir + '/' + mapperFile, 'utf8');
    
    for (const reqAttr of requiredAttrs) {
      if (!mapperContent.includes(reqAttr)) {
        // sometimes it maps like foo_bar to fooBar. Let's check snake_case too
        const snake = reqAttr.replace(/[A-Z]/g, letter => `_${letter.toLowerCase()}`);
        if (!mapperContent.includes(snake)) {
          console.log(`Model ${modelName} requires '${reqAttr}' but it's not found in ${mapperFile}`);
        }
      }
    }
  }
  process.exit();
})();
