require('dotenv').config();
const http = require('http');
const app = require('./app');
const logger = require('./utils/logger');
const { sequelize } = require('./models'); // Will be generated by sequelize-cli
const { Server } = require('socket.io');

process.on('uncaughtException', (err) => {
  logger.error('UNCAUGHT EXCEPTION! Shutting down...', err);
  process.exit(1);
});

process.on('unhandledRejection', (err) => {
  logger.error('UNHANDLED REJECTION! Shutting down...', err);
  process.exit(1);
});

const PORT = process.env.PORT || 5000;

const server = http.createServer(app);
const io = new Server(server, {
  cors: {
    origin: '*',
  }
});

app.set('io', io);

io.on('connection', (socket) => {
  logger.info(`User connected via socket: ${socket.id}`);
  socket.on('disconnect', () => {
    logger.info(`User disconnected: ${socket.id}`);
  });
});

const initializeCallCenterSockets = require('./modules/callcenter/sockets/callCenter.socket');
initializeCallCenterSockets(io);

const startServer = async () => {
  try {
    // Authenticate database connection
    await sequelize.authenticate();
    logger.info('Database connection has been established successfully.');

    // Auto-create super admin
    const { Role, User } = require('./models');
    try {
      let superAdminRole = await Role.findOne({ where: { name: 'SUPER_ADMIN' } });
      if (!superAdminRole) {
        superAdminRole = await Role.create({ name: 'SUPER_ADMIN', description: 'System Administrator' });
      }
      
      const phone = '998909086434';
      const existingAdmin = await User.findOne({ where: { phone } });
      if (!existingAdmin) {
        await User.create({
          firstName: 'Super',
          lastName: 'Admin',
          phone: phone,
          password: '6434',
          roleId: superAdminRole.id
        });
        logger.info('Super Admin created successfully with phone: ' + phone);
      }
    } catch (err) {
      logger.error('Failed to auto-create super admin:', err);
    }

    server.listen(PORT, '0.0.0.0', () => {
      logger.info(`Server is running on port ${PORT}`);
    });
  } catch (error) {
    logger.error('Unable to start server:', error);
    process.exit(1);
  }
};

startServer();
