require('dotenv').config();
const http = require('http');
const app = require('./app');
const logger = require('./utils/logger');
const { sequelize } = require('./models'); // Will be generated by sequelize-cli
const { Server } = require('socket.io');

const PORT = process.env.PORT || 5000;

const server = http.createServer(app);
const io = new Server(server, {
  cors: {
    origin: '*',
  }
});

app.set('io', io);

io.on('connection', (socket) => {
  logger.info(`User connected via socket: ${socket.id}`);
  socket.on('disconnect', () => {
    logger.info(`User disconnected: ${socket.id}`);
  });
});

const initializeCallCenterSockets = require('./modules/callcenter/sockets/callCenter.socket');
initializeCallCenterSockets(io);

const startServer = async () => {
  try {
    // Authenticate database connection
    await sequelize.authenticate();
    logger.info('Database connection has been established successfully.');

    server.listen(PORT, () => {
      logger.info(`Server is running on port ${PORT}`);
    });
  } catch (error) {
    logger.error('Unable to start server:', error);
    process.exit(1);
  }
};

startServer();
